#!/usr/bin/env bash

# refs: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -eo pipefail
IFS=$'\n\t'

CLI=$(basename "${BASH_SOURCE[0]}")

usage() {
    cat <<-EOF
Usage: $CLI <repo> <...paths> or $CLI <url>

> Download folders or files from GitHub repo without cloning

Arguments:
    <repo>               like: \`username/repo\`, if username is missing, it will use the gh's username
    <...paths>           folders or files path
    <url>                github url starts with https://github.com

Options:
    -h, --help           output usage
    -v, --version        output version
    --verbose            enable debug
    -d, --dry-run        reports what would have been downloaded, but do not download anything
    -b, --branch         branch or tag name
    --outdir <path>      only support download single path(file/folder). Default is download current location and reserved repo dir path
    --outfile <path>     only support download single file

Examples:
    gh download yuler/gh-download README.md gh-download
    gh download cli/cli .github
    gh download yuler/actions ci/nodejs.yml --outdir .github/workflows
EOF
    exit
}

version() {
    echo "$CLI v0.5.0"
    exit
}

# fix: #11
# refs: https://gist.github.com/cdown/1163649
urlencode_filename() {
    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C

    local length="${#1}"
    for ((i = 0; i < length; i++)); do
        local c="${1:$i:1}"
        case $c in
        [a-zA-Z0-9/.~_-]) printf '%s' "$c" ;;
        *) printf '%%%02X' "'$c" ;;
        esac
    done

    LC_COLLATE=$old_lc_collate
}

URLS=()

collection_file() {
    local file=$1
    local folder=$2
    local dest=$3

    # Normalize $folder must start with `./`
    if [[ ! $folder ]]; then
        folder="$(dirname "$file")"
    fi

    # Normalize $dest
    if [[ ! $dest && $outdir && $folder ]]; then
        if [[ $folder == "." ]]; then
            dest="$outdir/$file"
        else
            dest=${file/$folder/$outdir}
        fi
    fi
    if [[ $outfile ]]; then
        dest=$outfile
    fi
    if [[ ! $dest ]]; then
        dest=$file
    fi

    echo "Collection file: \`$file\` downloading to \`$dest\`"

    URLS+=("https://raw.githubusercontent.com/$repo/$branch/$(urlencode_filename "$file")" "$dest")
}

collection_folder() {
    local folder=$1

    echo "Collection folder: \`$folder\` downloading..."
    files=$(gh api "repos/$repo/git/trees/$branch?recursive=1" --jq ".tree[] | select(.type == \"blob\") | .path | select(startswith(\"$folder/\"))")
    for file in $files; do
        collection_file "$file" "$folder"
    done
}

# Parallel curl
function download() {
    if [[ $dry_run ]]; then
        exit
    fi
    parallel_args='--parallel-immediate --parallel'
    for ((i = 0; i < ${#URLS[@]}; i += 2)); do
        parallel_args+=" ${URLS[i]} --output ${URLS[i + 1]}"
    done
    command="curl --location --create-dirs --oauth2-bearer $token $parallel_args"
    eval "$command"
}

# Main
# refs: https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
# TODO: Move `getopts` refs: https://man7.org/linux/man-pages/man1/getopts.1p.html
POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
    -h | --help)
        usage
        ;;
    -v | --version)
        version
        ;;
    --verbose)
        set -x
        shift
        ;;
    -d | --dry-run)
        dry_run=true
        shift
        ;;
    -b | --branch)
        branch="$2"
        shift
        shift
        ;;
    --outdir)
        outdir="$2"
        shift
        shift
        ;;
    --outfile)
        outfile="$2"
        shift
        shift
        ;;
    *)
        POSITIONAL+=("$1")
        shift
        ;;
    esac
done
set -- "${POSITIONAL[@]}"

token=$(gh config get -h github.com oauth_token)

# TODO: check url from clipboard
# Parse argments from url
# Example: https://github.com/yuler/actions/blob/3541e20e6f195a812b0e775058224a6d6f4b9fc1/ci/nodejs.yml
regex="^https://github.com/([A-Za-z0-9_-]*)/([A-Za-z0-9._-]*)/(tree|blob)/([A-Za-z0-9._-]*)/(.*)"
if [[ $# == 1 ]]; then
    if [[ $1 =~ $regex ]]; then
        repo="${BASH_REMATCH[1]}/${BASH_REMATCH[2]}"

        branch="${BASH_REMATCH[4]}"
        path="${BASH_REMATCH[5]}"

        # TODO: Duplicated content below
        echo "Repo: $repo"
        echo "Branch: $branch"

        case "${BASH_REMATCH[3]}" in
        tree) collection_folder "$path" ;;
        blob) collection_file "$path" ;;
        esac
        download
        exit
    else
        echo "Parse url $1 error."
    fi
else
    repo=$1
    shift
fi

if [[ ! $repo =~ .*/.* ]]; then
    username=$(gh config get -h github.com user)
    repo=$username/$repo
fi

if [[ ! $branch ]]; then
    branch=$(gh api "repos/$repo" --jq .default_branch)
fi

echo "Repo: $repo"
echo "Branch: $branch"

# Download single path
if [[ $# == 1 ]]; then
    path=$1

    # TODO: Duplicated content below
    # Check path is folder?
    if [[ $path =~ .*/$ ]]; then
        folder=${path%/}
    else
        folder=$(gh api "repos/$repo/git/trees/$branch?recursive=1" --jq ".tree[] | select(.type == \"tree\") | .path | select(.==\"$path\")")
    fi

    if [[ $folder ]]; then
        collection_folder "$folder"
    else
        collection_file "$path"
    fi

    download
    exit
fi

# Unset `--outfile` option & `--outdir` option
unset outfile
unset outdir

# Iterate arguments
while (("$#")); do
    path=$1

    # Check path is folder?
    if [[ $path =~ .*/$ ]]; then
        folder=${path%/}
    else
        folder=$(gh api "repos/$repo/git/trees/$branch?recursive=1" --jq ".tree[] | select(.type == \"tree\") | .path | select(.==\"$path\")")
    fi

    if [[ $folder ]]; then
        collection_folder "$folder"
    else
        collection_file "$path"
    fi

    shift
done
download
