#!/bin/bash
set -eo pipefail
IFS=$'\n\t'

usage() {
    cat <<-EOF
Usage: gh download <repo> <folders | files>

> Download folders or files from GitHub repo with default branch

Arguments:
    <repo>               like: \`username/repo\`, if username is missing, it will use the gh's username
    <folders | files>    folders must end with \`/\`, otherwise they are file

Options:
    --output <path>      output path, default is \`./\`

Examples:
    gh download yuler/gh-download README.md gh-download
    gh download cli/cli .github/
    gh download yuler/actions ci/nodejs.yml --output ./.github/workflows/
EOF
}

download_file() {
    if [[ -z "output" ]]; then
        output="$1"
    else
        output="$output/$(basename $1)"
    fi
    echo "file $1 downloading..."
    curl --location --create-dirs --oauth2-bearer $token https://raw.githubusercontent.com/$repo/$default_branch/$1 -o $output
}

download() {
    if [[ $1 =~ */ ]]; then
        files=$(gh api repos/$repo/git/trees/$default_branch?recursive=1 --jq ".tree[] | select(.type == \"blob\") | .path | select(startswith(\"$1\"))")
        echo "folder $1 downloading..."
        for file in $files; do
            download_file $file
        done
    else
        download_file $1
    fi
}

# parse `--output` option
POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"

    case $key in
    --output)
        output="$2"
        shift # past argument
        shift # past value
        ;;
    *)                     # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift              # past argument
        ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

# main
if [[ -z $1 || $1 == '-h' || $1 == '--help' ]]; then
    usage
    exit 0
fi

token=$(gh config get -h github.com oauth_token)

repo=$1
shift
if [[ ! $repo =~ .*/.* ]]; then
    username=$(gh config get -h github.com user)
    repo=$username/$repo
    echo "GitHub repo: $repo"
fi

default_branch=$(gh api repos/${repo} --jq ".default_branch")

while (("$#")); do
    download $1
    shift
done
